/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Student {
  /**
   * 年龄
   */
  age: number | null;
  /**
   * 系统默认字段,创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 描述
   */
  desc: string | null;
  /**
   * 系统默认字段,唯一主键
   */
  id: Generated<number>;
  /**
   * 姓名
   */
  name: string | null;
  /**
   * 系统默认字段,更新时间
   */
  update_time: Generated<Date | null>;
}

export interface Teacher {
  /**
   * 年龄
   */
  age: string | null;
  /**
   * 系统默认字段,创建时间
   */
  create_time: Generated<Date | null>;
  /**
   * 描述
   */
  desc: string | null;
  /**
   * 系统默认字段,唯一主键
   */
  id: Generated<number>;
  /**
   * 姓名
   */
  name: string | null;
  /**
   * 系统默认字段,更新时间
   */
  update_time: Generated<Date | null>;
}

export interface DB {
  student: Student;
  teacher: Teacher;
}
